### ISSUE TITLE
Broken link to image

### ISSUE THREAD

**Issue by giordano** [JuliaParallel/julia-hpc-tutorial-sc24#7]
There's a broken link to an image at https://github.com/JuliaParallel/julia-hpc-tutorial-sc24/blob/59b22ffc98603a75fbadf6f30bbb6e09432475a0/parts/mpi/README.md#task-2---halo-exchange
https://github.com/JuliaParallel/julia-hpc-tutorial-sc24/blob/59b22ffc98603a75fbadf6f30bbb6e09432475a0/parts/mpi/README.md?plain=1#L28-L30 refers to a non-existent `visualisation.png` file, but in that directory there are two files called respectively `visualization_before.png` and `visualization_desired.png`, I presume this was supposed to be the latter? CC: @JBlaschke

**Comment by JBlaschke** [comment]
Thanks for bringing this to my attention -- I've fixed it.
